name: CI - Security Scan
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 0'
jobs:
  security:
    name: Analisis de vulnerabilidades
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - run: mvn org.owasp:dependency-check-maven:10.0.4:check -q
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
          retention-days: 30
